version: "3.8"
services:
  frontend:
    container_name: grafana_container
    build: ./backend
    restart: always
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true

  db:
    container_name: postgres_container
    image: andreluizigal/postgres_teachers_statistics:TCC
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "12345"
    ports:
      - "5000:5432"
    volumes:
      - data:/var/lib/postgresql/data

volumes:
  data: